version: "3"
services:
  mongo:
    container_name: r5_mongo
    image: mongo:4
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongodb-volume:/data/db:rw

  backend:
    image: majkshkurti/r5:latest
    container_name: backend_r5
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      JVM_HEAP_GB: 14
    links:
      - mongo
    ports:
      - "7070:7070"
      - "7080:7080"
    volumes:
      - ./r5-cache:/r5/cache

  ui:
    container_name: r5_ui
    image: majkshkurti/analysis-ui:latest
    # build:
    #   dockerfile: ./ui/Dockerfile
    #   context: .
    depends_on:
      - backend
    ports:
      - "3000:3000"
    links:
      - backend
    volumes: # (paths relative to the Compose file)
      - .env:/app/.env:ro

volumes:
  mongodb-volume:
